### ISSUE TITLE
 [discover] appears frozen when installing something, cannot be closed

### ISSUE THREAD

**Issue by AJSlye** [blue-systems/plasma-5.4#157]
Under Netrunner Rolling, Discover looks like it never finishes installing, it seems to be frozen but it just can't be closed while the install is not finished. Also,  it doesn't show progress bar (this works in kubuntu showing a fine line above the install task).

I filed a bug report to the Arch maintainer and it was closed:
https://bugs.archlinux.org/task/46519

**Comment by aleixpol** [comment]
I just tested using Plasma/5.4 branch and it worked.

Can you maybe check if there's some warning when running from the console?

**Comment by AJSlye** [comment]
![snapshot3](https://cloud.githubusercontent.com/assets/10186587/10333630/3ea29d7a-6cb3-11e5-842b-f446b983c942.png)

This is what I'm getting as you can see no progress bars and the close button does nothing.

**Comment by star-buck** [comment]
tried with latest kci:
simply search for chromium and click "Install", then chromium gets downloaded, but uon discover window cannot be closed.
Even when seemingly aborting the Install while clicking the red X on the install statusbar (which apparently only closes the statusbar, but user may think the install is now aborted), the window muon discover cannot be closed.
Since this might be a feature, maybe a simple reminder popup "Cannot close, installation still in progress" would be nice.

**Comment by aleixpol** [comment]
I agree this could be a usability problem, but I'm not sure if it's the same problem @AJSlye mentioned.

I'll introduce such warning though.

**Comment by AJSlye** [comment]
I was only reporting the issue that Star-buck conveyed to me. Instead of a worning a progress bar that shows that Muon is actually doing something, like it does in ubuntu derivatives would be a better option.

**Comment by aleixpol** [comment]
I've found some inconsistencies with the PackageKit progress reporting of transactions. I'll look into that first as it's a pure bug. Once the API usage is fixed I'll look into how we can make it clear that there's progress going on. The new design helps there, IMO.

**Comment by star-buck** [comment]
closing this here, continued under plasma5.5
