### ISSUE TITLE
[muon-updater]: creates lock-file error at startup with octopi/pacman/discover

### ISSUE THREAD

**Issue by NuLogicSystems** [blue-systems/plasma-5.4#158]
Muon updater runs at login and can take up to a min or two refreshing the repositories.
This is causing a lock file at first login and you can't use pacman, Discover or Octopi.
How can we speed this up?

**Comment by aleixpol** [comment]
Well, I'd say it's good that we're eventually updating the repository call. It can be probably delayed to a bit later.

When would you like this to happen? I think it's good if package cache update is transparent to the user.

**Comment by AJSlye** [comment]
Personally, I think Muon has enough issues under Arch that need to be fixed first, no progress bars, etc. However, I believe that this issue has more to do with mirror speed than the actual lock file itself.

**Comment by aleixpol** [comment]
Correct, the question is: Do you think it's unacceptable that the notifier plasmoid fetches updates on its own? Personally I like it, but I'm unsure how subjective my PoV is.

**Comment by AJSlye** [comment]
Personally I like it as well. This issue was originally brought to my attention by Clemens. On my system depending on the time of day, the worst I'm getting is 2 min. but on average it takes less than a min. However, apparently on his system it's over three minutes consistently.
Both issues were posted here:
http://wiki.netrunnerlinux.com/index.php/Netrunner_Rolling_2015.12

**Comment by AJSlye** [comment]
I'm not sure what would be best, on my system this takes less than a minute. Perhaps Since Clemens is the one that originally expressed this concern, we should wait for him to respond on the matter?
