### ISSUE TITLE
[system sounds]: notification sound is sometimes delayed or only emitted once

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#73]
* add 2 new folders to folderview:
* mark 1 folder and hit "Del" to move to trash-> confirmation dialog popup comes up with sound
* Del next one-> same dialog somes up, but no sound is heard

**Comment by mck182** [comment]
Looks like KNotification bug. I'll take a look.

**Comment by mck182** [comment]
Fixed with http://commits.kde.org/knotifications/55d6c866054ff09f1ab55ae68e85a9c39e6148cc

**Comment by star-buck** [comment]
awesome thanks! will try in next kci :)

**Comment by star-buck** [comment]
seems still delayed or shaky, not sure how to reproduce though...
will keep this open for a little longer...

**Comment by star-buck** [comment]
system sounds like "delete - confirmation popup notify sound" have a delay of about 2-3 seconds on several machines under plasma5 (under kde4 the notifiy sounds were almost immediately on same machines).

**Comment by mck182** [comment]
2-3 seconds sounds quite high o_O

So here's exactly what happens when the sound should be played for the first time in any application:
 * New KNotification object is created (in case of dialogs it's KNotification::event(..))
 * The config file with the sound file path is loaded
 * Phonon is initialized
 * Phonon is passed the file path from the config
 * Phonon plays sound

The only place where it could be slowed down is either the config file loading or Phonon initializing things or the sound file being loaded from disk. I don't think the config file loading can be speed up any further, so we'd have to look at Phonon.

Which Phonon backend is used on those systems?

**Comment by star-buck** [comment]
yeah, somtimes its <1sec, sometimes between 1-2 seconds and also sometimes longer... since using kde4 gets you trained like a pavlov dog to expect a sound here and there, you keep waiting for it under plasma5, and in case of > 2-3 seconds almost give up on it and go on and then the sound still gets played. :)
Phonon in Netrunner uses gstreamer backend default, I yet have to thouroughly test if this happens mainly under dolphin4 or also when adding files to folderview containment, then mark them and delete.
