### ISSUE TITLE
[virtualbox]: make gfx work normal in virtual machines

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#86]
Errata quote:
"for unknown reasons X/installer/sddm refuse to start in virtual machines (tested with vbox and kvm). the ISO therefore only does something useful when used on bare metal"

**Comment by davidedmundson** [comment]
It's a bug in virtualbox.
https://www.virtualbox.org/ticket/13615

Comment 1 suggests a workaround that might work.

**Comment by mgraesslin** [comment]
Bug comment #17 claims it's a bug in Ubuntu. Seems like bug ping-pong :-(

**Comment by apachelogger** [comment]
Isn't that resolved in 15.04 now?

**Comment by star-buck** [comment]
since i rarely test in Virtual machines, I cant really say...

**Comment by mgraesslin** [comment]
By pure chance I tested today and it's terrible. The guest extensions are not installed by default and it falls back to llvmpipe, which gives a rather sluggish experience everywhere.

Then I had the stupid idea to install the guest extensions, it gives you OpenGL, but it's so broken that nothing really works. I got a small KWin debug output visible and it was all over "called in this method didn't do what I expected". Looks like the driver announces GL extensions which it doesn't do.

On the VirtualBox I'm now using an OpenBox session as I wasn't able to revert to other settings easily.

**Comment by apachelogger** [comment]
Well, virtualbox always has been terrible which is why we originally decided that the team should test bare metal as much as possible ^^. BUT getting a sluggish experience in virtualbox is better than what was the original problem of epilepsy-rainbow-techno-mode as seen here
https://www.virtualbox.org/ticket/13615

So yeah, I am pretty sure the original issue here is fixed in 15.04 final. That's not to say that the virtualbox experience is enjoyable though.

**Comment by davidedmundson** [comment]
New images have worked in new virtualbox for me

**Comment by star-buck** [comment]
closing this now unless hearing otherwise.
